apiVersion: v2
name: massbank3
description: A helm chart for the MassBank 3 applications
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0
appVersion: "dev"

dependencies:
  - name: postgresql
    version: "~12.5.8"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mongodb
    version: "~13.15.3"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
